apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-crd
  labels:
    label-to-be-passed-to-managed-secret: sample-value
  annotations:
    example.com/annotation-to-be-passed-to-managed-secret: "sample-value"
spec:
  hostAPI: http://192.168.49.2:31596/api
  # hostAPI: http://infisical-backend.infisical.svc.cluster.local:4000/api
  resyncInterval: 10
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: project-infisical-llt1
        envSlug: dev
        secretsPath: "/"
      credentialsRef:
        secretName: infisicalsecret-universalauth-crd
        secretNamespace: default
  managedSecretReference:
    secretName: managed-secret
    secretNamespace: default
    creationPolicy: "Orphan"
    template:
      includeAllSecrets: true
      data:
        NEW_KEY_NAME: "{<!-- -->{ .KEY.SecretPath }} {<!-- -->{ .KEY.Value }}"
        KEY_WITH_BINARY_VALUE: "{<!-- -->{ .KEY.SecretPath }} {<!-- -->{ .KEY.Value }}"